### ISSUE TITLE
license

### ISSUE THREAD

**Issue by endomorphosis** [koh-osug/orbitdb-benchmark#1]
no license found.

**Comment by endomorphosis** [comment]
also, this is a much more straight forward "quickstart" than the official quickstart

**Comment by koh-osug** [comment]
OK, I added a license. I was not assuming that this is found by someone.

> no license found.

OK, I added a license. I was not assuming that this is found by someone.

**Comment by koh-osug** [comment]
> also, this is a much more straight forward "quickstart" than the official quickstart

Yes, I was also having with the simple example. Anyway, where I got stuck was:
* the query methods and get functions are using a linear search, e.g. if there are 10000 entries, then with bad luck 10000 entries are scanned to find the result. No keys are indexed.
* Adding data is slow if the batch insert is larger.
* how to build a safe local only deployment not talking to the internet and verifying peer IDs if they are known, e.g. signed by a local network only authority.

**Comment by endomorphosis** [comment]
https://github.com/ipfs/kubo/issues/10383#issuecomment-2035428115

I have had similar problems with ipfs not being optimized, I will close this issue (the license issue) and will link to this in an orbitdb issue you raised.
